weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/WeechatActivity.java
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/fragments/BufferFragment.java
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/fragments/BufferListFragment.java
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/RelayServiceBackbone.java
weechat-android/src/main/res/values/strings.xml
weechat-relay/src/main/java/com/ubergeek42/weechat/relay/RelayConnection.java
weechat-relay/src/main/java/com/ubergeek42/weechat/relay/RelayConnectionHandler.java
weechat-relay/src/main/java/com/ubergeek42/weechat/relay/connection/AbstractConnection.java
weechat-relay/src/main/java/com/ubergeek42/weechat/relay/connection/IConnection.java

The app now displays a simple toast when it is assumed that the password is wrong. The logic is the same as in glowing bear, assuming the wrong password was the reason for the disconnect. Weechat relay terminates the connection right after checking the init command if the password was bad.

Notify user if relay password is wrong

---

weechat-relay/src/main/java/com/ubergeek42/weechat/Color.java

Hey there!
When nick coloring is enabled, the dark blue nicks are invisible on my phone. This image illustrates the problem, and the improved blue:

Lightened the "Dark blue" color so that blue nicks are visible

---

weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/SSLCertActivity.java

When presenting the certificate details to be verified, make known to the user *which* fingerprint is being shown.

Be specific about hash type in certificate details

---

weechat-android/src/main/res/values/strings.xml

"Hot message!" in notification drop down has slightly sexual connotations. If that's the intention, following a particular sense of humor: fine and funny. If not, I am sure I am not the only one who noticed that so that's why I propose a change from "Hot" to (neutral) "New".

change notification messages from "Hot" to "New"

---

weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/utils/CopyPaste.java

Sometimes it is desireable to only copy the content of a message so you
do not have to strip out the prefix etc..

Added plain message content to copy menu

---

weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/adapters/NickListAdapter.java
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/relay/Buffer.java
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/relay/BufferList.java
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/relay/Nick.java
weechat-android/src/main/res/values/style.xml

This implements the #269 feature request.
Summary:
- adds a new `style.xml` color (a light blue extracted from Glowing Bear)
- parses the `color` nick attribute that contains `[…].nicklist_away` if user is away
- stores the away status (a bool) into a new attribute of class `Nick`
- modifies the `NickListAdapter` to set the color of away nicks

Distinguish away nicks in nick list using a light blue color

---

weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/adapters/NickListAdapter.java

This is a fixup for 7e89bb5. Android heavy cache makes the adapter "leak" the away color to nicknames that are not away as the user scrolls within the list (this recycles holders w/ their color, hence the "leak").
To fix that, we cache the default color on first load and then apply it on the textview for both away/online statuses.
--
Sorry for the two PRs. I should have further tested that feature before submitting.

Fix wrong away nick color caused by cache

---

weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/P.java
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/RelayService.java
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/SSLHandler.java
weechat-relay/src/main/java/com/ubergeek42/weechat/relay/connection/SSLConnection.java

This partially fixes #266. Implementing for SSL WebSockets is not possible unless we use development release that gives access to `setSocket()`.
All the magic resides in the use of Android's `SSLCertificateSocketFactory` which implements hostname verification in its [`createSocket()`](https://developer.android.com/reference/android/net/SSLCertificateSocketFactory.html).

Implement hostname verification for connection type ‘Weechat SSL’

---

.travis.yml
build.gradle
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/P.java
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/RelayService.java
weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/SSLHandler.java
weechat-relay/build.gradle
weechat-relay/src/main/java/com/ubergeek42/weechat/relay/connection/WebSocketConnection.java

Follow-up for #266.
- use *jitpack.io* to add dependency to Java-WebSocket [current HEAD](/TooTallNate/Java-WebSocket/commit/58d17786958ec2b629b75de1eed00915b3e4f7c4)
- remove `sslContext`! yay!
- use `sslSocketFactory` to build the websocket socket, now that we can use `setSocket()`

Use Java-WebSocket master to add hostname vertification

---

weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/fragments/BufferFragment.java

Allows the buffer scroll position to be retained when changing activity (eg. click on a link) or state change (eg. screen rotation).

Save buffer position on fragment stop to restore it on fragment start

---

weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/fragments/BufferFragment.java

Crash stacktrace:
> 08-14 13:15:00.572  4023  4023 D AndroidRuntime: Shutting down VM
08-14 13:15:00.579  4023  4023 E AndroidRuntime: FATAL EXCEPTION: main
08-14 13:15:00.579  4023  4023 E AndroidRuntime: Process: com.ubergeek42.WeechatAndroid.dev, PID: 4023
08-14 13:15:00.579  4023  4023 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.AdapterView.getFirstVisiblePosition()' on a null object reference
08-14 13:15:00.579  4023  4023 E AndroidRuntime: 	at com.ubergeek42.WeechatAndroid.fragments.BufferFragment.onSaveInstanceState(BufferFragment.java:149)
08-14 13:15:00.579  4023  4023 E AndroidRuntime: 	at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2112)
08-14 13:15:00.579  4023  4023 E AndroidRuntime: 	at …

Fix NPE on using invalid uiLines

---

weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/PingActionReceiver.java

Fixes #347. Since changing the setting in the menu does not immediately start the `PingActionReceiver`, checking `P.pingEnabled` is not enough and just catching the exception is the cleaner way.

Fix crash when ping is disabled

---

app/src/main/java/com/ubergeek42/WeechatAndroid/service/SSLHandler.java

i'm not sure how this worked in the first place, but it definitely shouldn't have. anyway, the bug it fixes somehow only showed up once i updated to android P.

fix socket closed before getting certificate

---

app/src/main/AndroidManifest.xml

Super simple change that will make my life much easier as someone that does rom development and needs to be able to hop phones quickly via adb backup/restore.
This is one of the only apps I use that for some reason does not have backups enabled. The user still has to approve on the unlocked device for every backup, so I don't see any security risk here.

Allow backups

---

app/proguard-rules.pro

Without this, when connecting to WeeChat SSL, WA dies with: "Cannot
verify hostname".

Don't strip apache lib for SSL on Android 6

---

app/src/main/AndroidManifest.xml
app/src/main/java/androidx/preference/FontManager.java
app/src/main/java/androidx/preference/FontPreference.java
app/src/main/java/androidx/preference/ThemeManager.java
app/src/main/java/androidx/preference/ThemePreferenceHelp.java
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml

Android Q denies access to external storage to apps by default.
This will request legacy storage access. Also, it allows loading files from app-specific directory (e.g. `/storage/emulated/0/Android/data/com.ubergeek42.WeechatAndroid/files/fonts`).
Loading files from `weechat` folder can be perhaps removed altogether later on along with the storage permission.

Fix storage access on Android Q

---

app/src/main/java/com/ubergeek42/WeechatAndroid/CutePagerTitleStrip.java

Update the displayed text when the empty text is set, otherwise it won't happen until connecting causes an update.

Fix display of version on startup

---

app/proguard-rules.pro
app/src/main/java/androidx/preference/PrivateKeyPickerPreference.java
app/src/main/java/com/ubergeek42/WeechatAndroid/utils/AndroidKeyStoreUtils.java
app/src/main/java/com/ubergeek42/WeechatAndroid/utils/AndroidKeyStoreUtils.kt

this requires a few classes from BouncyCastle, apk size +238K
for pkcs1, BC seems to support aes*, des, des3 ciphers, and does not support aria*, camellia* and idea despite including the ciphers
for pkcs8, BC seems to support every cipher from v1 (PBE-MD5-DES, PBE-SHA1-RC2-64, PBE-MD5-RC2-64, PBE-SHA1-DES, PBE-SHA1-RC4-128, PBE-SHA1-RC4-40, PBE-SHA1-3DES, PBE-SHA1-2DES, PBE-SHA1-RC2-128, PBE-SHA1-RC2-40, couldn't test as couldn't generate: PBE-MD2-DES and PBE-MD2-RC2-64) and des3 from v2, but not des or rc2 for some reason
in other words, this should support every PEM key that's created in modern openssh and openssl unless you try to be funny

Support keys in PKCS#8 format

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/ubergeek42/WeechatAndroid/notifications/Notificator.kt
app/src/main/java/com/ubergeek42/WeechatAndroid/service/PingActionReceiver.java
app/src/main/java/com/ubergeek42/WeechatAndroid/service/SyncAlarmReceiver.java
app/src/main/java/com/ubergeek42/WeechatAndroid/views/AlphaLayout.kt
cats/build.gradle.kts

Fixes #535, see there for context. For the most part, upgrading `appcompat` to 1.4 was sufficient, except for the main chat view where using `EmojiCompat` directly was necessary, as described [here](https://developer.android.com/guide/topics/ui/look-and-feel/emoji2#no-widgets).
<details>
<summary>Screenshot</summary>
</details>

Fix emoji rendering on Android 11 and older

---

app/src/main/java/com/ubergeek42/WeechatAndroid/dialogs/NicklistDialog.kt

When clicking on a nick on the nicklist, the `/query` command is issued, causing the relay to switch its buffer to the query.  weechat-android should switch the *client* buffer instead (see #538), but leave the relay buffer intact.
If the relay buffer is switched, it may cause missed notifications due to weechat  incorrectly believing that messages have been seen on the relay, since the buffer is opened.
Fixes #550

Keep relay buffer when clicking on the nicklist

---

app/src/main/java/com/ubergeek42/WeechatAndroid/fragments/BufferFragment.kt
app/src/main/java/com/ubergeek42/WeechatAndroid/service/P.java
app/src/main/java/com/ubergeek42/WeechatAndroid/utils/Constants.java
app/src/main/java/com/ubergeek42/WeechatAndroid/utils/History.kt
app/src/main/java/com/ubergeek42/WeechatAndroid/utils/MigratePreferences.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/values.xml
app/src/main/res/xml/preferences.xml

The navigation state is saved and restored along with BufferFragment's lifecycle.
The deprecated preference is migrated to the correspondig volume role.
Supersedes #297. Fixes #553.

Implement roles for volume buttons: do nothing, change text size, navigate sent history

---

app/src/main/java/com/ubergeek42/WeechatAndroid/fragments/BufferFragment.kt
app/src/main/java/com/ubergeek42/WeechatAndroid/service/P.java
app/src/main/java/com/ubergeek42/WeechatAndroid/utils/Constants.java
app/src/main/java/com/ubergeek42/WeechatAndroid/utils/History.kt
app/src/main/java/com/ubergeek42/WeechatAndroid/utils/MigratePreferences.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/values.xml
app/src/main/res/xml/preferences.xml

Please see #554 comments.
* Similar behavior to Weechat native input
* Don't store whitespace-only messages
* Prevent navigation if user has non-uploaded ShareSpans, and display an error toast

Volume buttons: implement Weechat-like input history rather than sent history

---

app/build.gradle.kts
app/src/main/java/com/ubergeek42/WeechatAndroid/fragments/BufferFragment.kt
app/src/main/java/com/ubergeek42/WeechatAndroid/upload/MediaAcceptingEditText.kt
app/src/main/java/com/ubergeek42/WeechatAndroid/upload/ShareObject.kt
build.gradle.kts

See individual commits.
For drag n drop, the entire buffer fragment acts like a drop target.
I'm not sure whether or not we need drag-n-drop indicators, like the ones you see in Gmail. One one hand, we normally only show a single buffer. On the other, it might be somewhat useful to indicate that the buffer list or the title bar are not targets for dropping files. I decided to not do any indicators because I am lazy and who even drags and drops files on Android anyway.

Allow drag n drop & fix a few issues with file sharing

---

app/build.gradle.kts
app/src/main/java/androidx/preference/FullScreenEditTextPreference.java
app/src/main/java/com/ubergeek42/WeechatAndroid/service/P.java
build.gradle.kts
cats/build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Needed to go forward. See individual commit messages.

Update Gradle & AGP to version 8

---

app/src/main/java/com/ubergeek42/WeechatAndroid/adapters/ChatLinesAdapter.kt
app/src/main/java/com/ubergeek42/WeechatAndroid/relay/Buffer.kt
app/src/main/java/com/ubergeek42/WeechatAndroid/relay/BufferList.kt
app/src/main/java/com/ubergeek42/WeechatAndroid/relay/Line.kt

See individual commits & their messages. I hope this doesn't break things, will require a bit of hands-on testing.

Survive `/buffer clear`
